### ISSUE TITLE
Adding image localization and force resolution

### ISSUE THREAD

**Issue by SunRed** [josueespinosa/BingBackground#2]
Would it be possible adding a config.xml read by the program where the country code can be set? This would make it possible to download the 'localized' image given by json from something like `"https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=" + countryCode` instead of the default one. E.g. I am german so it would be `countryCode="de-DE"`.
Also it would be a great addition to force a specific resolution if the appropriate file exists instead of just checking the resolution of the device. This may be useful if the device just has a weird resolution and don't want to download a file with 1920x1080 pixels.
I may come up with a pull request but C# isn't my programming language so it would be a pleasure if you just have an idea for the implementation.
Also I could just change these things in the program and recompile it but it would be easier for those who are not in programming. :wink:

Nice tool though and keep up the good work ofc! :+1:

**Comment by josueespinosa** [comment]
Yes! I will investigate this further when I get some free time, thank you for the notes!

**Comment by SunRed** [comment]
Also, there are some more or less useful forks: 
[csmith1210](https://github.com/csmith1210/BingBackground)
[drasockalypse](https://github.com/drasockalypse/BingBackground)
